services:
  - type: web
    name: firecracker-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: MQTT_BROKER_URL
        value: mqtt://broker.hivemq.com
